create table person (
                       id integer generated by default as identity primary key ,
                       name varchar unique not null ,
                       birth integer check ( birth>1800 and birth<3000 ),
                       fine numeric(15, 2) default 0.0
);

create table book (
                     id integer generated by default as identity primary key ,
                     title varchar not null,
                     author varchar not null,
                     year integer check ( year < 3000 ),
                     person_id integer references person(id) on delete set null,
                     taking_date date,
                     expiry_date date
);

create table transaction (
    id integer generated by default as identity primary key,
    debtor integer references person(id),
    receiving_bank integer,
    sending_account integer,
    receiving_account integer,
    amount numeric(15, 2),
    transaction_currency char(3) not null,
    transaction_status varchar(9) default 'PENDING'
);